# -*- coding: utf-8 -*-
"""Training and Testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QOsx1RRNA9fzxBu4NAsl6JLq8hcJ7Njh
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive

!mkdir -p ~/.kaggle
!cp /content/drive/MyDrive/kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!ls ~/.kaggle

!pip install -q kaggle

!ls "/content/drive/MyDrive/preprocessed dataset/preprocessed dataset"

train_path = "/content/drive/MyDrive/preprocessed dataset/preprocessed dataset/training"
test_path  = "/content/drive/MyDrive/preprocessed dataset/preprocessed dataset/testing"

!ls "$train_path"
!ls "$test_path"

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import Xception
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.models import Model

imageSize = [299, 299]

trainPath = r"/content/drive/MyDrive/preprocessed dataset/preprocessed dataset/training"
testPath  = r"/content/drive/MyDrive/preprocessed dataset/preprocessed dataset/testing"

from tensorflow.keras.layers import Dense, Flatten, Input
from tensorflow.keras.models import Model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img
from tensorflow.keras.applications.xception import Xception, preprocess_input
from glob import glob
import numpy as np
import matplotlib.pyplot as plt

train_datagen = ImageDataGenerator(
    rescale=1./255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True
)

test_datagen = ImageDataGenerator(rescale=1./255)

training_set = train_datagen.flow_from_directory(
    trainPath,
    target_size=(299, 299),
    batch_size=32,
    class_mode='categorical'
)

test_set = test_datagen.flow_from_directory(
    testPath,
    target_size=(299, 299),
    batch_size=32,
    class_mode='categorical'
)

xception = Xception(
    input_shape=imageSize + [3],
    weights='imagenet',
    include_top=False
)

for layer in xception.layers:
    layer.trainable = False

x = Flatten()(xception.output)
prediction = Dense(5, activation='softmax')(x)

model = Model(inputs=xception.input, outputs=prediction)

model.summary()

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

r = model.fit(
    training_set,
    validation_data=test_set,
    epochs=10,
    steps_per_epoch=len(training_set),
    validation_steps=len(test_set)
)

model.save("/content/drive/MyDrive/Updated-Xception-diabetic-retinopathy.h5")